export const AllFrames = {
    "default":"/pixelart/character.png",
    "back":"/pixelart/character-back.png",
    "blinkFrames":[
        "/pixelart/animate/Blink/step-1.png",
        "/pixelart/animate/Blink/step-2.png",
        "/pixelart/animate/Blink/step-1.png",
        ],
    "walkFrames":[
    "/pixelart/animate/Forward/step-1.png",
    "/pixelart/animate/Forward/step-2.png"
    ],
    "jumpFrames":[
        "/pixelart/animate/Jump/jump1.png",
        "/pixelart/animate/Jump/jump2.png",
        "/pixelart/animate/Jump/jump3.png",
        "/pixelart/animate/Jump/jump2.png",
        "/pixelart/animate/Jump/jump1.png"
    ],
    "waveFrames":[
        "/pixelart/animate/wave/step1.png",
        "/pixelart/animate/wave/step2.png"
    ]
}